docker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    
  script:
    - docker build -t $CI_REGISTRY_USER/ms-menu:latest .
    - docker push $CI_REGISTRY_USER/ms-menu:latest
  only:
    - develop


